<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	Translation to Bulgarian (c) 2013, Nikolay Hamov, http://tonove.info/
	
	File: qa-lang/qa-include/qa-lang-main.php
	Version: 1.6.2
	Date: 2013-10-05 10:32:00 GMT
	Description: Language phrases commonly used throughout Q2A

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'_decimal_point' => ",",
		'_thousands_separator' => " ",
		'_thousands_suffix' => " хил.",
		'_millions_suffix' => " мил.",
		'1_answer' => '1 отговор',
		'1_comment' => '1 коментар',
		'1_day' => '1 ден',
		'1_disliked' => '1 неодобрение',
		'1_flag' => '1 флаг',
		'1_hour' => '1 час',
		'1_liked' => '1 одобрение',
		'1_minute' => '1 минута',
		'1_month' => '1 месец',
		'1_point' => '1 точка',
		'1_question' => '1 въпрос',
		'1_second' => '1 секунда',
		'1_tag' => '1 етикет',
		'1_user' => '1 потребител',
		'1_view' => '1 преглед',
		'1_vote' => '1 глас',
		'1_week' => '1 седмица',
		'1_year' => '1 година',
		'email_error' => "Възникна грешка докато се изпраща този емейл.",
		'file_upload_limit_exceeded' => "Размера на файла надвишава ограниченията на сървъра",
		'since_x' => "от ^",
		'to_x' => "до ^",
		'add_category_x_favorites' => 'Добави категория ^ към любимите ми',
		'add_favorites' => 'Добави към любимите ми',
		'add_tag_x_favorites' => 'Добави етикета ^ към любимите ми',
		'all_categories' => 'Всички категории',
		'anonymous' => 'анонимен',
		'answer_edited' => 'отговорът е редактиран',
		'answer_reshown' => 'отговорът е показан отново',
		'answer_selected' => 'отговорът е избран',
		'answered_qs_in_x' => 'Въпросите, на които е отговаряно най-много в ^',
		'answered_qs_title' => 'Въпросите, на които е отговаряно най-много',
		'answered' => 'отговорени',
		'asked_related_q' => 'попита свързан въпрос',
		'asked' => 'попитан',
		'by_x' => 'от ^',
		'cancel_button' => 'Отмени',
		'closed' => 'затворен',
		'comment_edited' => 'коментарът е редактиран',
		'comment_moved' => 'коментарът е преместен',
		'comment_reshown' => 'коментарът е показан отново',
		'commented' => 'коментиран',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^year ^month ^day',
		'date_format_this_year' => '^day ^month',
		'date_month_1' => 'януари',
		'date_month_2' => 'февруари',
		'date_month_3' => 'март',
		'date_month_4' => 'април',
		'date_month_5' => 'май',
		'date_month_6' => 'юни',
		'date_month_7' => 'юли',
		'date_month_8' => 'август',
		'date_month_9' => 'септември',
		'date_month_10' => 'октомври',
		'date_month_11' => 'ноември',
		'date_month_12' => 'декември',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'редактиран',
		'field_required' => 'Моля, въведете нещо в това поле',
		'general_error' => 'Случи се грешка в сървъра - моля опитайте отново.',
		'hidden' => 'скрит',
		'highest_users' => 'Потребители с най-много точки',
		'hot_qs_in_x' => 'Горещи въпроси в ^',
		'hot_qs_title' => 'Горещи въпроси',
		'image_not_read' => 'Изображението не можа да се прочете. Моля качете някое от: ^',
		'image_too_big_x_pc' => 'Изображението е твърде голямо. Моля намалете го до ^% и опитайте отново.',
		'in_category_x' => 'в ^',
		'ip_address_x' => 'IP адрес ^',
		'logged_in_x' => 'Здравейте ^',
		'max_length_x' => 'Максималната дължина е ^ знака',
		'me' => 'аз',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Моля добавете още информация (поне ^ знака)',
		'max_upload_size_x' => 'Максималният размер за качване е ^',
		'moved' => 'преместен',
		'nav_activity' => 'Активност',
		'nav_admin' => 'Администриране',
		'nav_ask' => 'Задай въпрос',
		'nav_categories' => 'Категории',
		'nav_feedback' => 'Обратна връзка',
		'nav_home' => 'Главна страница',
		'nav_hot' => 'Горещо!',
		'nav_login' => 'Влез',
		'nav_logout' => 'Излез',
		'nav_most_answers' => 'С повече отговори',
		'nav_most_recent' => 'Последни',
		'nav_most_views' => 'С повече прегледи',
		'nav_most_votes' => 'С повече гласове',
		'nav_no_answer' => 'Без отговор',
		'nav_no_selected_answer' => 'Няма избран отговор',
		'nav_no_upvoted_answer' => 'Няма отговор',
		'nav_qa' => 'Въпроси и Отговори',
		'nav_qs' => 'Въпроси',
		'nav_register' => 'Регистрация',
		'nav_tags' => 'Етикети',
		'nav_unanswered' => 'Неотговорени',
		'nav_updates' => 'Моите обновления',
		'nav_users' => 'Потребители',
		'newest_users' => "Най-нови потребители",
		'no_active_users' => 'Няма активни потребители',
		'no_answers_found' => 'Няма отговори',
		'no_answers_in_x' => 'Няма отговори в ^',
		'no_categories_found' => 'Няма категории',
		'no_category' => 'Няма категория',
		'no_comments_found' => 'Не са намерени коментари',
		'no_comments_in_x' => 'Няма коментари в ^',
		'no_questions_found' => 'Няма намерени въпроси',
		'no_questions_in_x' => 'Няма въпроси в ^',
		'no_related_qs_title' => 'Няма намерени свързани въпроси',
		'no_results_for_x' => 'Не са намерени резултати за ^',
		'no_tags_found' => 'Не са намерени етикети',
		'no_una_questions_found' => 'Не са намерени неотговорени въпроси',
		'no_una_questions_in_x' => 'Няма неотговорени въпроси в ^',
		'no_unselected_qs_found' => 'Няма намерени въпроси без избран отговор',
		'no_unupvoteda_qs_found' => 'Няма намерени въпроси без надгласуван отговор',
		'page_label' => 'Страница:',
		'page_next' => 'следваща',
		'page_not_found' => 'Страницата не е намерена',
		'page_prev' => 'предишна',
		'popular_tags' => 'Най-популярни етикети',
		'questions_tagged_x' => 'Последни въпроси етикетирани ^',
		'recategorized' => 'прекатегоризирани',
		'recent_activity_in_x' => 'Последна активност в ^',
		'recent_activity_title' => 'Последна активност',
		'recent_as_in_x' => 'Скоро отговорени въпроси в ^',
		'recent_as_title' => 'Скоро отговорени въпроси',
		'recent_cs_in_x' => 'Скоро добавени коментари в ^',
		'recent_cs_title' => 'Скоро добавени коментари',
		'recent_qs_as_in_x' => 'Последно добавени въпроси и отговори в ^',
		'recent_qs_as_title' => 'Последно добавени въпроси и отговори',
		'recent_qs_in_x' => 'Последни въпроси в ^',
		'recent_qs_title' => 'Последни въпроси',
		'related_qs_title' => 'Подобни въпроси',
		'remove_favorites' => 'Remove from my favorites',
		'remove_favorites' => 'Изтрий от любимите ми',
		'remove_x_favorites' => 'Изтрий ^ от любимите ми',
		'reopened' => 'отворен отново',
		'reshown' => 'показан отново',
		'results_for_x' => 'Резултати от търсенето за ^',
		'retagged' => 'етикетиран отново',
		'save_button' => 'Запази промените',
		'search_button' => 'Търси',
		'search_explanation' => 'Моля, въведете текст в полето за търсене и опитайте отново.',
		'search_title' => 'Резултати от търсенето',
		'selected' => 'избран',
		'send_button' => 'Изпрати',
		'suggest_ask' => 'Помогнете да започне нова дискусия като ^1зададете въпрос^2.',
		'suggest_category_qs' => 'За да видиш още, кликни за всичките ^1въпроси от тази категория^2.',
		'suggest_qs_tags' => 'За да видиш още, кликни за ^1пълния списък на въпросите^2 или ^3популярните етикети^4.',
		'suggest_qs' => 'За да видиш още, кликни за ^1пълния списък на въпросите^2.',
		'unanswered_qs_in_x' => 'Последни въпроси без отговор в ^',
		'unanswered_qs_title' => 'Последни въпроси без отговор',
		'unselected_qs_in_x' => 'Въпроси без избран отговор в ^',
		'unselected_qs_title' => 'Последни въпроси без избран отговор',
		'unupvoteda_qs_in_x' => 'Въпроси без надгласуван отговор в ^',
		'unupvoteda_qs_title' => 'Последни въпроси без надгласуван отговор',
		'upload_limit' => 'Твърде много качвания - опитай отново след час',
		'view_q_must_be_approved' => 'Вашият профил трябва да бъде одобрен преди да можете да видите страниците с въпроси. Моля, изчакайте или ^1добавете още информация^2.',
		'view_q_must_confirm' => 'Моля ^5потвърдете своя мейл адрес^6 за да видиш страниците с въпроси.',
		'view_q_must_login' => 'Моля ^1влезте^2 или се ^3регистрирайте^4 за да видиш страниците с въпроси.',
		'viewed_qs_in_x' => 'Най-преглеждани въпроси в ^',
		'viewed_qs_title' => 'Най-разглежданите въпроси',
		'vote_disabled_approve' => 'Вашият профил трябва да въде одобрен преди да можете да гласувате',
		'vote_disabled_down' => 'Отрицателното гласуване и достъпно само за някои потребители',
		'vote_disabled_down_approve' => 'Вашият профил трябва да бъде одобрен преди да можете да гласувате отрицателно',
		'vote_disabled_hidden_a' => 'Не може да гласувате за скрити отговори',
		'vote_disabled_hidden_post' => "Не може да гласувате за скрити постове",
		'vote_disabled_hidden_q' => 'Не може да гласувате за скрити въпроси',
		'vote_disabled_level' => 'Гласуването е достъпно само за някои потребители',
		'vote_disabled_my_a' => 'Не може да гласувате за своите отговори',
		'vote_disabled_my_q' => 'Не може да гласувате за своите въпроси',
		'vote_disabled_q_page_only' => 'Моля разгледай този въпрос за да гласуваш',
		'vote_disabled_my_post' => "Не може да гласувате за своите постове",
		'vote_disabled_queued' => "Може да гласувате само за одобрени постове",
		'vote_down_must_confirm' => 'Моля, ^5потвърдете Вашия мейл адрес^6, за да гласувате отрицателно.',
		'vote_down_popup' => 'Кликнете за да гласувате неодобрение',
		'vote_limit' => 'Твърде много гласове са получени - моля опитайте отново след час',
		'vote_must_confirm' => 'Моля ^5потвърдете Вашия мейл адрес^6 за да гласувате.',
		'vote_must_login' => 'Моля ^1влезте^2 или се ^3регистрирайте^4 за да гласувате.',
		'vote_not_allowed' => 'Гласуването за това не е разрешено',
		'vote_up_popup' => 'Кликнете за да гласувате одобрение',
		'voted_down_popup' => 'Гласували сте неодобрение - кликнете за го премахнете',
		'voted_qs_in_x' => 'Най-високо оценените въпроси в ^',
		'voted_qs_title' => 'Най-високо оценените въпроси',
		'voted_up_popup' => 'Гласували сте одобрение - кликнете за да го премахнете',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => 'преди ^',
		'x_answers' => '^ отговори',
		'x_comments' => '^ коментари',
		'x_days' => '^ дни',
		'x_disliked' => '^ неодобрения',
		'x_flags' => '^ флагове',
		'x_hours' => '^ часа',
		'x_liked' => '^ одобрения',
		'x_minutes' => '^ минути',
		'x_months' => '^ месеца',
		'x_points' => '^ точки',
		'x_questions' => '^ въпроса',
		'x_seconds' => '^ секунди',
		'x_tags' => '^ етикети',
		'x_users' => '^ потребителя',
		'x_views' => '^ прегледа',
		'x_votes' => '^ гласа',
		'x_weeks' => '^ седмици',
		'x_years' => '^ години',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
