<?php

/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	Translation to Bulgarian (c) 2013, Nikolay Hamov, http://tonove.info/
	
	File: qa-lang/bg/qa-lang-options.php
	Version: 1.6.2
	Date: 2013-10-05 10:12:00 GMT
	Description: Language phrases for admin center

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_anonymous_naming' => "Позволи на анонимни потребители да задават имената си:",
		'allow_change_usernames' => 'Позволи на потребители с постове да сменят имената си:',
		'allow_close_own_questions' => "Позволи на потребителите да затварят собствените си въпроси:",
		'default_terms' => "Съгласен съм с ^ Условията и Полицата за поверителност",
		'page_size_pms' => "Лични съобщения на страница:",
		'show_post_update_meta' => "Покажи редактирай/обнови в post мета:",
		'show_register_terms' => "Избиране на Условията в регистрационната форма - HTML позволен:",
		'site_text_direction' => "Посока на текста в сайта:",
		'allow_close_questions' => 'Позволи въпросите да се затварят ръчно: ',
		'allow_login_email_only' => 'Логване само чрез мейл адрес (не потребителско име)',
		'allow_multi_answers' => 'Позволи многобройни отговори от потребител:',
		'allow_no_category' => 'Позволи въпроси без категория',
		'allow_no_sub_category' => 'Позволи въпроси с катогерия, но без подкатегория',
		'allow_private_messages' => 'Позволи на потребителите да си изпращат лични съобщения:',
		'allow_user_walls' => 'Позволи постове на стените на потребителските профили: ',
		'allow_self_answer' => 'Позволи на потребителите да отговарят на собствените си въпроси:',
		'allow_view_q_bots' => 'Позволи на търсачките да виждат страниците с въпроси',
		'approve_user_required' => 'Всички нови потребители трябва да бъдат одобрявани: ',
		'avatar_allow_gravatar' => 'Позволи аватари от ^1Gravatar^2:',
		'avatar_allow_upload' => 'Позволи на потребителите да си качват аватари:',
		'avatar_default_show' => 'Покажи аватар по подразбиране:',
		'avatar_message_list_size' => 'Размер на аватара на списъците със съобщения:',
		'avatar_profile_size' => 'Размер на аватар на страница с профил (пиксели):',
		'avatar_q_list_size' => 'Размер на аватар в списъка с въпроси (пиксели):',
		'avatar_q_page_a_size' => 'Размер на аватар в отговорите (пиксели):',
		'avatar_q_page_c_size' => 'Размер на аватар в коментарите (пиксели):',
		'avatar_q_page_q_size' => 'Размер на аватар във въпросите (пиксели):',
		'avatar_store_size' => 'Максимален размер на запазените аватари (пиксели):',
		'avatar_users_size' => 'Размер на аватарите на страницата на най-добрите потребители (пиксели):',
		'block_bad_words' => 'Цензурирани думи (разделени с интервали или запетаи):',
		'block_bad_usernames' => "Забранени потребителски имена (разделени с интервали или запетаи):",
		'block_ips_write' => 'Блокирани IP адреси (разделени с интервали или запетаи):',
		'caching_catwidget_time' => "Cache category widget for:",
		'caching_enabled' => "Активирано кеширане:",
		'caching_driver' => "Драйвер за кеширане",
		'caching_filesystem' => "Файлова система",
		'caching_memcached' => "Memcached",
		'caching_q_start' => "Започни кеширане на въпроси след:",
		'caching_q_time' => "Кеширай страници на въпроси за:",
		'caching_qlist_time' => "Кеширай списък с въпроси за:",
		'captcha_module' => 'Използвай captcha модул:',
		'captcha_on_anon_post' => 'Използвай reCAPTCHA за анонимни постове:',
		'captcha_on_feedback' => 'Използвай reCAPTCHA за формата за обратна връзка:',
		'captcha_on_register' => 'Използвай reCAPTCHA за регистрация:',
		'captcha_on_reset_password' => 'Използвай reCAPTCHA за формата за смяна на паролата:',
		'captcha_on_unapproved' => 'Използвай captcha ако потребителят не е одобрен:',
		'captcha_on_unconfirmed' => 'Използвай reCAPTCHA за постове ако няма потвърден е-мейл:',
		'columns_tags' => 'Колони на страниците с етикети:',
		'columns_users' => 'Колони на страниците с потребители:',
		'comment_on_as' => 'Позволи коментари на отговорите:',
		'comment_on_qs' => 'Позволи коментари на въпросите:',
		'confirm_user_emails' => 'Искай потвърждение на е-мейлите на потребителите:',
		'confirm_user_required' => 'Всички нови потребители трябва да потвърдят техния е-мейл:',
		'custom_home_content' => 'Съдържание, което да се покаже на главната страница (HTML е разрешен):',
		'custom_home_heading' => 'Заглавие, което да се покаже на върха на главната страница:',
		'default_privacy' => 'Конфиденциалност: Вашият е-мейл няма да бъде споделян или продаван на трети лица.',
		'default_sidebar' => "Добре дошли в ^, където можете да задавате въпроси на хора със знания и опит, както и да споделяте знанията и опита си с другите.",
		'default_subject' => 'Съобщение от ^',
		'default_suffix' => 'В и О',
		'do_ask_check_qs' => 'Проверявай за подобни въпроси при питане:',
		'do_close_on_select' => 'Затваряй въпросите с избран отговор:',
		'do_complete_tags' => 'Показвай съвпадащи етикети при писане:',
		'do_count_q_views' => 'Брой прегледите на въпросите:',
		'do_example_tags' => 'Показвай примерни етикети базирани на въпроса:',
		'editor_for_as' => 'Редактор по подразбиране за отговорите:',
		'editor_for_cs' => 'Редактор по подразбиране за коментарите:',
		'editor_for_qs' => 'Редактор по подразбиране за въпросите:',
		'email_privacy' => 'Бележка за конфиденциалност за е-мейловете на всички форми (HTML е позволен):',
		'extra_field_active' => 'Поле за допълнителна информация на формата за питане:',
		'extra_field_display_label' => 'Покажи допълнителна информация на страниците с въпроси с етикет:',
		'extra_field_display' => 'Покажи допълнителна информация на страниците с въпроси',
		'feed_for_activity' => 'Фийд за скорошна активност:',
		'feed_for_hot' => 'Фийд за горещи въпроси:',
		'feed_for_qa' => 'Фийд за последни въпроси и отговори:',
		'feed_for_questions' => 'Фийд за последни въпроси:',
		'feed_for_search' => 'Фийд за резултати от търсенето:',
		'feed_for_tag_qs' => 'Фийд за последни въпроси с всеки етикет:',
		'feed_for_unanswered' => 'Фийд за последни неотговорени въпроси:',
		'feed_full_text' => 'Включвай пълния текст във фийдовете:',
		'feed_number_items' => 'Максимален брой на нещата във фийдовете:',
		'feed_per_category' => 'Фийдове за горното във всяка категория:',
		'feedback_email' => 'Е-мейл адрес за административни съобщения (не се показва на потребителите):',
		'feedback_enabled' => 'Осигури на потребителите форма за обратна връзка',
		'flagging_hide_after' =>'Автоматично скривай постове, които достигнат:',
		'flagging_notify_every' => 'Пращай е-мейл за всички допълнителни:',
		'flagging_notify_first' => 'Пращай е-мейл щом пост получи:',
		'flagging_of_posts' => 'Позволи постовете да бъдат отбелязвани като неподходящи:',
		'follow_on_as' => 'Позволи новите отговори да бъдат свързвани с отговори:',
		'from_email' => 'Изпращач за всички административни съобщения:',
		'hot_weight_a_age' => 'Относително тегло на последния отговор за горещината:',
		'hot_weight_answers' => 'Относително тегло на броя отговори за горещината:',
		'hot_weight_q_age' => 'Относително тегло на възрастта на въпроса за горещината:',
		'hot_weight_views' => 'Относително тегли на броя прегледи за горещината:',
		'hot_weight_votes' => 'Относително тегло на вотовете за горещината:',
		'links_in_new_window' => 'Отваряй въведените линкове в нов прозорец:',
		'logo_height' => 'Височина на логото в пиксели:',
		'logo_show' => 'Показвай лого в хедъра на страниците',
		'logo_url' => 'URL на логото (абсолютен или относителен спрямо QA корена):',
		'logo_width' => 'Ширина на логото в пиксели:',
		'mailing_body' => 'Тяло за изпращане',
		'mailing_enabled' => 'Позволи масовите е-мейли към потребителите',
		'mailing_from_email' => 'Изходящ мейл адрес:',
		'mailing_from_name' => 'Изходящо име:',
		'mailing_per_minute' => 'Максимална скорост на изпращане',
		'mailing_subject' => 'Относно:',
		'match_1' => 'Най-тясно',
		'match_2' => 'По-тясно',
		'match_3' => 'По подразбиране',
		'match_4' => 'По-широко',
		'match_5' => 'Най-широко',
		'match_ask_check_qs' => 'Търсене на подобни въпроси:',
		'match_example_tags' => 'Търсене на примерни етикети:',
		'match_related_qs' => 'Търсене на свързани въпроси:',
		'max_len_q_title' => 'Маскимален брой знаци в заглавието на въпрос:',
		'max_num_q_tags' => 'Максимален брой етикети на въпрос:',
		'max_rate_ip_as' => 'Максимален брой отговори на IP на час:',
		'max_rate_ip_cs' => 'Максимален брой коментари на IP на час:',
		'max_rate_ip_flags' => 'Максимален брой флагове на IP на час:',
		'max_rate_ip_logins' => 'Максимален брой опити за влизане на IP на час:',
		'max_rate_ip_messages' => 'Максимален брой лични съобщения на IP на час:',
		'max_rate_ip_qs' => 'Максимален брой въпроси на IP адрес на час:',
		'max_rate_ip_registers' => 'Максимална интензивност на новите регистрации:',
		'max_rate_ip_uploads' => 'Максимален брой качвания на IP на час:',
		'max_rate_ip_votes' => 'Максимален брой гласувания на IP на час:',
		'max_rate_user_as' => 'Максимален брой отговори на потребител на час:',
		'max_rate_user_cs' => 'Максимален брой коментари на потребител на час:',
		'max_rate_user_flags' => 'Максимален брой флагове на потребител на час:',
		'max_rate_user_messages' => 'Максимален брой лични съобщения на потребител на час:',
		'max_rate_user_qs' => 'Максимален брой въпроси на потребител адрес на час:',
		'max_rate_user_uploads' => 'Максимален брой качвания на потребител на час:',
		'max_rate_user_votes' => 'Максимален брой гласувания на потребител на час:',
		'min_len_a_content' => 'Минимален брой знаци в отговор:',
		'min_len_c_content' => 'Минимален брой знаци в коментар:',
		'min_len_q_content' => 'Минимален брой знаци в описанието на въпрос:',
		'min_len_q_title' => 'Минимален брой знаци в заглавието на въпрос:',
		'min_num_q_tags' => 'Минимален брой етикети на въпрос:',
		'minify_html' => "Minify HTML:",
		'moderate_anon_post' => 'Използвай модерация за анонимните постове:',
		'moderate_by_points' => 'Използвай модерация за потребителите с малко точки',
		'moderate_edited_again' => 'Премодерирай постовете след редакция:',
		'moderate_notify_admin' => 'Изпрати ми е-мейл ако е необходима модерация',
		'moderate_points_limit' => 'Използвай модерация за потребители с по-малка от:',
		'moderate_unapproved' => 'Използвай модерация ако потребителят все-още не е одобрен:',
		'moderate_unconfirmed' => 'Използвай модерация ако е-мейлът не е потвърден:',
		'moderate_update_time' => 'Време за показване на модерираните постове:',
		'moderate_users' => 'Включи модерация (одобрение) на потребителите:',
		'neat_urls' => 'URL структура на страниците на сайта:',
		'notify_admin_q_post' => 'Изпрати ми мейл на този адрес когато се постави въпрос',
		'notify_users_default' => 'Чекни бокса за нотификация по е-мейл по подразбиране:',
		'option_default' => 'По подразбиране',
		'page_size_activity' => 'Дължина на страницата за всичката активност:',
		'page_size_ask_check_qs' => 'Максимална дължина на подобните въпроси:',
		'page_size_ask_tags' => 'Минималния брой подсказки за етикети:',
		'page_size_home' => 'Дължина на главната страница:',
		'page_size_hot_qs' => 'Дължина на страницата с горещи въпроси:',
		'page_size_q_as' => 'Максимум отговори на страница:',
		'page_size_qs' => 'Дължина на страницата с въпроси:',
		'page_size_related_qs' => 'Максимален брой свързани въпроси:',
		'page_size_search' => 'Въпроси на страницата за търсене:',
		'page_size_tag_qs' => 'Въпроси на страницата с етикетите:',
		'page_size_tags' => 'Дължина на страницата с етикетите:',
		'page_size_una_qs' => 'Дължина на страницата с неотговорените въпроси:',
		'page_size_users' => 'Дължина на страницата с потребителите:',
		'page_size_wall' => 'Постове на стената на страница:',
		'pages_prev_next' => 'Линкове съм предишни/следващи страници:',
		'permit_admins' => 'Администратори',
		'permit_all' => 'Всеки',
		'permit_approve_users' => 'Одобряване на регистрираните потребители:',
		'permit_approved' => 'Само одобрени потребители',
		'permit_approved_points' => 'Одобрени потребители с достатъчно точки',
		'permit_block' => 'Брокирани или разблокиране на потребител или IPs:',
		'permit_confirmed' => 'Регистрирани потребители с потвърден е-мейл',
		'permit_create_admins' => 'Създаване на администратори:',
		'permit_create_eds_mods' => 'Създаване на редактори и модератори:',
		'permit_create_experts' => 'Създаване на ескперти:',
		'permit_delete_users' => 'Изтриване на потребители',
		'permit_editors' => 'Редактори, Модератори, Администратори',
		'permit_experts' => 'Експерти, Редактори, Модератори, Администратори',
		'permit_moderators' => 'Модератори и Администратори',
		'permit_points_confirmed' => 'Регистрирани, с потвърден е-мейл и с достатъчно точки',
		'permit_points' => 'Регистрирани потребители с достатъчно точки',
		'permit_see_emails' => 'Разглеждане на потребителските е-мейл адресиs:',
		'permit_supers' => 'Супер Администратори',
		'permit_users' => 'Регистрирани потребители',
		'place_full_below_content' => 'Пълна ширина - Под съдържанието',
		'place_full_below_footer' => 'Пълна ширина - Под футъра',
		'place_full_below_nav' => 'Пълна ширина - Под навигацията',
		'place_full_top' => 'Пълна ширина - Върха на страницата',
		'place_main_below_lists' => 'Главната площ - Под списъците',
		'place_main_below_title' => 'Главната площ - Под заглавието',
		'place_main_bottom' => 'Главната площ - Дъното',
		'place_main_top' => 'Главната площ - Върха',
		'place_side_below_categories' => 'Страничен панел - Под категориите',
		'place_side_below_sidebar' => 'Страничен панел - Под кутията на страничния панел',
		'place_side_last' => 'Страничния панел - Последно',
		'place_side_top' => 'Страничния панел - Връх',
		'place_side_low' => "Страничния панел - Долу",
		'points_a_selected' => 'Точки за най-добър отговор:',
		'points_a_voted_max_gain' => 'Лимитиране на одобренията за всеки отговор:',
		'points_a_voted_max_loss' => 'Лимитиране на неодобренията за всеки отговор:',
		'points_c_voted_max_gain' => "Лимитиране на одобренията за всеки коментар:",
		'points_c_voted_max_loss' => "Лимитиране на неодобренията за всеки коментар:",
		'points_per_c_voted_down' => "За отрицателно гласуване на Ваш коментар:",
		'points_per_c_voted_up' => "За положително гласуване на Ваш коментар:",
		'points_base' => 'Добавяне за всеки потребител:',
		'points_multiple' => 'Умножение на всички точки:',
		'points_per_a_voted_down' => 'За отрицателно гласуване на Ваш отговор:',
		'points_per_a_voted_up' => 'За положително гласуване на Ваш отговор:',
		'points_per_q_voted_down' => 'За отрицателно гласуване на Ваш въпрос:',
		'points_per_q_voted_up' => 'За положително гласуване на Ваш въпрос:',
		'points_post_a' => 'Постване на отговор:',
		'points_post_q' => 'Постване на въпрос:',
		'points_q_voted_max_gain' => 'Лимитиране на одобренията за всеки въпрос:',
		'points_q_voted_max_loss' => 'Лимитиране на неодобренията за всеки въпрос:',
		'points_select_a' => 'Избор на най-добрия отговор за твоя въпрос:',
		'points_vote_down_a' => 'Гласуване неодобрение на отговор:',
		'points_vote_down_q' => 'Гласуване неодобрение на въпрос:',
		'points_vote_up_a' => 'Гласуване одобрение на отговор:',
		'points_vote_up_q' => 'Гласуване одобрение на въпрос:',
		'recalc_hotness_q_view' => "Recalculate hotness on every question page view:",
		'register_notify_admin' => 'Изпрати ми е-мейл когато нов потребител се регистрира:',
		'q_urls_remove_accents' => 'Махане на ударенията от URL-и във въпрос:',
		'q_urls_title_length' => 'Дължина на заглавието на въпроса в URL-ите:',
		'search_module' => 'Използвай модул за търсене:',
		'show_a_form_immediate' => 'Покажи форма за отговор незабавно:',
		'show_always' => 'Винаги',
		'show_c_reply_buttons' => 'Показвай бутони за отговори за коментарите:',
		'show_compact_numbers' => "Показване на обобщени цифри (пр. 1.3 хил.):",
		'show_custom_answer' => 'Произволно съобщение на формата за отговори - HTML е разрешен:',
		'show_custom_ask' => 'Произволно съобщение на формата за питане - HTML е разрешен:',
		'show_custom_comment' => 'Произволно съобщение на формата за коментари - HTML е разрешен:',
		'show_custom_footer' => 'Показвай HTML на дъното на всяка страница:',
		'show_custom_header' => 'Показвай HTML на върха на всяка страница:',
		'show_custom_home' => 'Съдържание на главната страница (вместо В и О)',
		'show_custom_in_head' => 'Произволен HTML в HEAD секцията на всяка страница:',
		'show_custom_register' => 'Произволно съобщение на формата за регистрация - HTML е разрешен:',
		'show_custom_sidebar' => 'Произволен HTML в кутията на страничната лента на всяка страница:',
		'show_custom_sidepanel' => 'Произволен HTML в страничния панел на всяка страница:',
		'show_custom_welcome' => 'Произволно съобщение в е-мейла изпращан на новорегистрираните потребители:',
		'show_fewer_cs_count' => 'Ако са частично скрити, покажи най-последните:',
		'show_fewer_cs_from' => 'Частично скрий коментарите ако са повече от:',
		'show_full_date_days' => 'Покажи пълна дата след:',
		'show_home_description' => 'Включи META описание на главната страница:',
		'show_if_no_as' => 'Ако няма отговори',
		'show_message_history' => 'Запази и показвай историята на личните съобщения:',
		'show_never' => 'Никога',
		'show_notice_visitor' => 'Съобщение отгоре за новите посетители - HTML е разрешен:',
		'show_notice_welcome' => 'Съобщение отгоре за новорегистрираните потребители - HTML е разрешен:',
		'show_selected_first' => 'Премести избрания отговор на върха:',
		'show_url_links' => 'Намери и свържи URL-те във въведения текст:',
		'show_user_points' => 'Показвай точки до имената на потребителите:',
		'show_user_titles' => 'Показвай заглавия до имената на потребителите:',
		'show_view_counts' => 'Показвай броя прегледи на въпросите:',
		'show_view_count_q_page' => 'Покажи броя показвания на страниците с въпроси:',
		'show_when_created' => 'Показвай възрастта на потребителското съдържание:',
		'site_language' => 'Език за Вашия сайт:',
		'site_maintenance' => 'Свали сайта за поддръжка',
		'site_theme_mobile' => 'Тема за мобилни апарати:',
		'site_theme' => 'Визуална тема за сайта:',
		'site_title' => 'Име на сайта за имената на страниците:',
		'site_url' => 'URL за използване при споменаване на сайта:',
		'smtp_active' => 'Изпращай мейл през SMTP вместо през локално',
		'smtp_address' => 'Адрес на SMPT сървъра:',
		'smtp_authenticate' => 'Изпрати SMTP потребител и парола',
		'smtp_password' => 'SMTP парола',
		'smtp_port' => 'Порт на SMTP сървъра:',
		'smtp_secure_none' => 'Няма',
		'smtp_secure' => 'SMTP криптирана връзка:',
		'smtp_username' => 'SMTP потребител:',
		'sort_answers_by' => 'Сортиране на отговорите по:',
		'sort_time' => 'Време',
		'sort_votes' => 'Вотове',
		'suspend_register_users' => 'Временно прекрати регистрацията на нови потребители:',
		'tag_separator_comma' => 'Използвай запетая като разделител за етикетите:',
		'tags_or_categories' => 'Класифицирай въпросите чрез използване на:',
		'time_approved' => 'Време на одобряване',
		'time_written' => 'Време на записване',
		'use_microdata' => "Използвай schema.org microdata:",
		'votes_separated' => 'Показвай отделните одобрение и неодобрения:',
		'voting_on_as' => 'Позволи гласуване за отговорите:',
		'voting_on_cs' => "Позволи гласуване за коментари:",
		'voting_on_q_page_only' => 'Позволи гласиване само на страницата на въпроса:',
		'voting_on_qs' => 'Позволи гласуването за въпросите:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
